# Copyright (c) 2018 JSONx
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# You should have received a copy of The MIT License (MIT) along with this
# program. If not, see <http://opensource.org/licenses/MIT/>.

language: bash
before_script:
- 'wget "https://archive.apache.org/dist/xerces/j/Xerces-J-bin.2.12.0.tar.gz" && tar zxpf Xerces-J-bin.2.12.0.tar.gz'
script:
- 'for FILE in schema-*/*.jsdx examples/*.jsdx; do
     RESULT=`java -classpath xerces-2_12_0/xercesImpl.jar:xerces-2_12_0/xml-apis.jar:xerces-2_12_0/xercesSamples.jar sax.Counter -v -n -np -s -f $* $FILE 2>&1`;
     echo $RESULT;
     [ -n "`echo $RESULT | grep Error`" ] && exit 1;
   done; exit 0'
